
# Builds a dockerimage and then runs tests from within the docker enviroment

name: CI with docker build
on:
  pull_request:
    branches:
    - main  # this takes around 90 mins to build the image, hence limiting to occational PRs

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and test with Docker
        run: |
          docker build -t paramak-neutronics --build-arg cq_version=2.1 --build-arg compile_cores=2 .

          docker run --rm paramak-neutronics  /bin/bash -c "cd example_01_single_volume_cell_tally && bash run_all.sh"
          docker run --rm paramak-neutronics  /bin/bash -c "cd example_02_multi_volume_cell_tally && bash run_all.sh"

          docker run --rm paramak-neutronics  /bin/bash -c "cd example_04_multi_volume_regular_mesh_tally && bash run_all.sh"
          docker run --rm paramak-neutronics  /bin/bash -c "cd example_05_3D_unstructured_mesh_tally && bash run_all.sh"

