
# This CI will lauch a Docker image that contains all the dependencies required
# within that image the pytest test suite is run 

name: CI with install

on:
  pull_request:    
    branches:
    - develop
    - main
 
jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fusion-energy/fusion-neutronics-workflow:dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: run example_01_single_volume_cell_tally
        run: |
          cd example_01_single_volume_cell_tally
          python 1_create_cad_and_convert_to_dagmc.py
          python 2_run_neutronics_simulation.py
        
      - name: run example_02_multi_volume_cell_tally
        run: |
          cd example_02_multi_volume_cell_tally
          python 1_create_cad_and_convert_to_dagmc.py
          python 2_run_neutronics_simulation.py      
 
      - name: run example_04_multi_volume_regular_mesh_tally
        run: |
          cd example_04_multi_volume_regular_mesh_tally
          python 1_create_cad_and_convert_to_dagmc.py
          python 2_run_neutronics_simulation.py       

      - name: run example_05_3D_unstructured_mesh_tally
        run: |
          cd example_05_3D_unstructured_mesh_tally
          python 1_create_cad_and_convert_to_dagmc.py
          mbconvert stage_2_output/unstructured_mesh.cub stage_2_output/unstructured_mesh.h5m
          python 2_run_neutronics_simulation.py
