
# Builds a dockerimage and then runs tests from within the docker enviroment

name: CI with docker build
on:
  pull_request:
    branches:
    - main  # this takes around 90 mins to build the image, hence limiting to occational PRs

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and test with Docker
        run: |
          docker build -s -t fusion-neutronics-workflow --build-arg cq_version=2.1 --build-arg compile_cores=2 .

          docker run --rm fusion-neutronics-workflow  /bin/bash -c "cd examples/example_01_single_volume_cell_tally && bash run_all.sh"
          docker run --rm fusion-neutronics-workflow  /bin/bash -c "cd examples/example_02_multi_volume_cell_tally && bash run_all.sh"
          docker run --rm fusion-neutronics-workflow  /bin/bash -c "cd examples/example_04_multi_volume_regular_mesh_tally && bash run_all.sh"

          # commented out as cubit learn license is currently not working
          # docker run --rm fusion-neutronics-workflow  /bin/bash -c "cd examples/example_05_3D_unstructured_mesh_tally && bash run_all.sh"
