
# This yml file will trigger a Github Action on release creation.
# This Action will build and upload a Docker image to GHCR
# https://github.com/marketplace/actions/publish-docker

name: docker-publish-release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  upload_workflow_output_files_to_release:
    # needs: build_and_push_release

    runs-on: ubuntu-latest

    name: 'create_files'

    container:
      image: ghcr.io/fusion-energy/fusion-neutronics-workflow

      - name: run example_01_single_volume_cell_tally
        run: |
          cd example_01_single_volume_cell_tally
          python 1_create_cad_and_convert_to_dagmc.py
          python 2_run_neutronics_simulation.py
        
      - name: run example_02_multi_volume_cell_tally
        run: |
          cd example_02_multi_volume_cell_tally
          python 1_create_cad_and_convert_to_dagmc.py
          python 2_run_neutronics_simulation.py      
 
      - name: run example_04_multi_volume_regular_mesh_tally
        run: |
          cd example_04_multi_volume_regular_mesh_tally
          python 1_create_cad_and_convert_to_dagmc.py
          python 2_run_neutronics_simulation.py       

      - name: run example_05_3D_unstructured_mesh_tally
        run: |
          cd example_05_3D_unstructured_mesh_tally
          python 1_create_cad_and_convert_to_dagmc.py
          mbconvert stage_2_output/unstructured_mesh.cub stage_2_output/unstructured_mesh.h5m
          python 2_run_neutronics_simulation.py

      - name: Upload artifact for CI
        uses: actions/upload-artifact@v2
        with:
          name: output_files_produced.zip
          path: output_files_produced.zip
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn` 

      - name: compress files
        run: |
          apt-get -y update
          apt-get -y install zip
          zip -r output_files_produced.zip example_*

      - name: Upload files into the release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: output_files_produced.zip
          asset_name: output_files_produced.zip
          tag: ${{ github.ref }}
