
# This yml file will trigger a Github Action on release creation.
# This Action will build and upload a Docker image to GHCR
# https://github.com/marketplace/actions/publish-docker

name: docker-publish-release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build_and_push_docker_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/fusion-energy/fusion-neutronics-workflow:embree
          build-args: |
            include_avx=false
            build_double_down=ON
            cq_version=2.1
            compile_cores=2
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/fusion-energy/fusion-neutronics-workflow:embree-avx
          build-args: |
            include_avx=true
            build_double_down=ON
            cq_version=2.1
            compile_cores=2

      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/fusion-energy/fusion-neutronics-workflow
          build-args: |
            include_avx=true
            build_double_down=OFF
            cq_version=2.1
            compile_cores=2

  upload_workflow_output_files_to_release:
    needs: build_and_push_docker_images
    runs-on: ubuntu-latest

    name: 'create_files'

    container:
      image: ghcr.io/fusion-energy/fusion-neutronics-workflow

    steps:
      - uses: actions/checkout@v2

      # the examples also appear on the docker image but they are in the
      # /examples subfolder so there is no overlap with these examples
      - name: run example_01_single_volume_cell_tally
        run: |
          cd example_01_single_volume_cell_tally
          python 1_create_cad_and_convert_to_dagmc.py
          python 2_run_neutronics_simulation.py
        
      - name: run example_02_multi_volume_cell_tally
        run: |
          cd example_02_multi_volume_cell_tally
          python 1_create_cad_and_convert_to_dagmc.py
          python 2_run_neutronics_simulation.py      
 
      - name: run example_04_multi_volume_regular_mesh_tally
        run: |
          cd example_04_multi_volume_regular_mesh_tally
          python 1_create_cad_and_convert_to_dagmc.py
          python 2_run_neutronics_simulation.py       
          python 3_post_process_and_plot.py

#       - name: run example_05_3D_unstructured_mesh_tally
#         run: |
#           cd example_05_3D_unstructured_mesh_tally
#           python 1_create_cad_and_convert_to_dagmc.py
#           mbconvert stage_2_output/unstructured_mesh.cub stage_2_output/unstructured_mesh.h5m
#           python 2_run_neutronics_simulation.py

      - name: compress files
        run: |
          apt-get -y update
          apt-get -y install zip
          zip -r output_files_produced.zip example_*

      - name: Upload artifact for CI
        uses: actions/upload-artifact@v2
        with:
          name: output_files_produced.zip
          path: output_files_produced.zip
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn` 

      - name: Upload files into the release
        uses: svenstaro/upload-release-action@v2
        with:
          overwrite: true
          tag: ${{ github.ref }}
          file: output_files_produced.zip
          asset_name: output_files_produced.zip
          repo_token: ${{ secrets.GITHUB_TOKEN }}

          
